import os
from .contracts import *
from .twsclient import *
from .twsclientqt import *
from .histrequester import *
from .twslogger import *
from . import util

__all__ = (['util'] + contracts.__all__ + twsclient.__all__ +
           twsclient.__all__ + histrequester.__all__)

AVAILABLE_TICK_TYPES = {
    0: 'Bid_Size',
    1: 'Bid_Price',
    2: 'Ask_Price',
    3: 'Ask_Size',
    4: 'Last_Price',
    5: 'Last_Size',
    6: 'High',
    7: 'Low',
    8: 'Volume',
    9: 'Close_Price',
    10: 'Bid_Option_Computation',
    11: 'Ask_Option_Computation',
    12: 'Last_Option_Computation',
    13: 'Model_Option_Computation',
    14: 'Open_Tick',
    15: 'Low_13_Weeks',
    16: 'High_13_Weeks',
    17: 'Low_26_Weeks',
    18: 'High_26_Weeks',
    19: 'Low_52_Weeks',
    20: 'High_52_Weeks',
    21: 'Average_Volume',
    22: 'Open_Interest',
    23: 'Option_Historical_Volatility',
    24: 'Option_Implied_Volatility',
    25: 'Option_Bid_Exchange',
    26: 'Option_Ask_Exchange',
    27: 'Option_Call_Open_Interest',
    28: 'Option_Put_Open_Interest',
    29: 'Option_Call_Volume',
    30: 'Option_Put_Volume',
    31: 'Index_Future_Premium',
    32: 'Bid_Exchange',
    33: 'Ask_Exchange',
    34: 'Auction_Volume',
    35: 'Auction_Price',
    36: 'Auction_Imbalance',
    37: 'Mark_Price',
    38: 'Bid_EFP_Computation',
    39: 'Ask_EFP_Computation',
    40: 'Last_EFP_Computation',
    41: 'Open_EFP_Computation',
    42: 'High_EFP_Computation',
    43: 'Low_EFP_Computation',
    44: 'Close_EFP_Computation',
    45: 'Last_Timestamp',
    46: 'Shortable',
    47: 'Fundamental_Ratios',
    48: 'RT_Volume',
    49: 'Halted',
    50: 'Bid_Yield',
    51: 'Ask_Yield',
    52: 'Last_Yield',
    53: 'Custom_Option_Computation',
    54: 'Trade_Count',
    55: 'Trade_Rate',
    56: 'Volume_Rate',
    57: 'Last_RTH_Trade',
    58: 'RT_Historical_Volatility',
    59: 'IB_Dividends',
    60: 'Bond_Factor_Multiplier',
    61: 'Regulatory_Imbalance',
    62: 'News',
    63: 'Short-Term_Volume_3_Minutes',
    64: 'Short-Term_Volume_5_Minutes',
    65: 'Short-Term_Volume_10_Minutes',
    66: 'Delayed_Bid',
    67: 'Delayed_Ask',
    68: 'Delayed_Last',
    69: 'Delayed_Bid_Size',
    70: 'Delayed_Ask_Size',
    71: 'Delayed_Last_Size',
    72: 'Delayed_High_Price',
    73: 'Delayed_Low_Price',
    74: 'Delayed_Volume',
    75: 'Delayed_Close',
    76: 'Delayed_Open',
    77: 'RT_Trade_Volume',
    78: 'Creditman_mark_price',
    79: 'Creditman_slow_mark_price',
    80: 'Delayed_Bid_Option',
    81: 'Delayed_Ask_Option',
    82: 'Delayed_Last_Option',
    83: 'Delayed_Model_Option',
    84: 'Last_Exchange',
    85: 'Last_Regulatory_Time',
    86: 'Futures_Open_Interest',
    87: 'Average_Option_Volume',
    88: 'Delayed_Last_Timestamp',
}

ROOT_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))